google-modules: gpu: Fix compilation when !MALI_CSF_SUPPORT
The gpu_debug_(read|dump)_pdc_status functions depend on
MALI_CSF_SUPPORT, not MALI_USE_CFS.

Use the correct guarding to stub out these functions when
pixel_gpu_debug is compiled out.

This resolves the following link-time error:

/usr/lib/gcc/aarch64-linux-gnu/14.2.0/../../../../aarch64-linux-gnu/bin/ld: Unexpected GOT/PLT entries detected!
/usr/lib/gcc/aarch64-linux-gnu/14.2.0/../../../../aarch64-linux-gnu/bin/ld: Unexpected run-time procedure linkages detected!
/usr/lib/gcc/aarch64-linux-gnu/14.2.0/../../../../aarch64-linux-gnu/bin/ld: vmlinux.o: in function `kbase_gpu_timeout_debug_message.lto_priv.0':
(.text+0xdf869c): undefined reference to `gpu_debug_dump_pdc_status'
collect2: error: ld returned 1 exit status
make[2]: *** [../scripts/Makefile.vmlinux:34: vmlinux] Error 1
make[1]: *** [/home/0ctobot/Android/google/komodo/neutrino/neutrino_kernel_google_caimito/Makefile:1342: vmlinux] Error 2
make: *** [Makefile:266: __sub-make] Error 2

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>